name: 12 - Working with Outputs
on:
  workflow-dispatch:
      inputs:
          build-status:
             description: testing
             type: choice 
             options:
                  - success
                  - failure
jobs: 
  build:
    runs-on: ubuntu-latest
    steps: 
         - name: Print GITHUB_OUTPUT path
           run: echo ${{GITHUB_OUTPUT}}  
                           