name: 02 - Workflow Events
on:
    push:
    pull_request:
    schedule:
        - cron: '30 17 * * *'
    workflow_dispatch:    
jobs:
  echo:
    runs-on: ubuntu-latest
    steps: 
        - name: Show the trigger
          run: echo "${{(github.event_name)}}"