name: 04 - Using Actions
on: 
    push:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
         - name: checking put the branch 
           uses: actions/checkout@v4
        
         - name: Setup Node
           uses: actions/setup-node@v4
           with:
             node-version: '20'  

         - name: Check Node and NPM versions
           run: |
             node -v
             npm -v

    