name: 07 - Using Expressions
on:
    push: 
    workflow_dispatch:
         inputs:
             debug:
                description: test
                type: boolean
                default: false


jobs:
    echo:
      runs-on: ubuntu-latest
      steps:
         - name: [debug] Print start-up data
           if: ${{ (inputs.debug) }}
           run: |
                echo "Triggered by: ${{(github.event_name)}}"
                echo "Branch: ${{(github.ref)}}"
                echo "Commit SHA: ${{github.sha}}"
                echo "Runner OS: ${{RUNNER_OS}}"
         - name: [debug] Print when triggered from main       
           if: ${{(inputs.debug) && (github.ref ==  main")}}
           run:  echo "tets"
