name: 10 - Controlling the Execution Flow
on:
    workflow_dispatch:
        inputs:
            pass-unit-tests:
                   type: boolean
                   description: "pass-unit-tests"
                   default: false
jobs:
    lint-build:
        runs-on: ubuntu-latest
        steps: 
             - name: Lint and build
               run: echo ""Linting and building project"
    unit-tests:
        runs-on: ubuntu-latest
        steps: 
            - name: Running unit tests
              run: echo "Running tests..."

            - name: Failing tests
              if: ${{ inputs.pass-unit-tests }} 
              run: |
                   exit 1
    deploy-nonprod:
        runs-on: ubuntu-latest
        if: "${{success()}}"
        steps:
            - name: Deploying to nonprod
              run: echo "Deploying to nonprod..."
    
    e2e-tests:
        runs-on: ubuntu-latest
        if: "${{success()}}"
        steps: 
            - name: deploy-nonprod
              run: |
                echo " Running E2E tests"
     
    load-tests:
        runs-on: ubuntu-latest
        if: ${{success()}}
        steps:
            - name: Running load tests
              run: "Running load tests"
      
    deploy-prod:
        runs-on: ubunut-latest
        if: ${{success()}}
        steps:
              - name: Deploying to prod
                run: "Deploying to prod..."


    

    
